version: '3.5'  

services: 
    redis: 
      image: bitnami/redis:latest
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      container_name: redis
    backend: 
      build:
        context: ./backend
      ports: 
        - 8000:8000
      container_name: server
      environment:
        - REDIS=redis
    frontend: 
      build:
        context: ./frontend
      ports: 
        - 5000:5000
      container_name: client
