version: '3.2'
services:
  calculator:
      build: ./calculator
      image: calculator
      ports:
        - 3000:3000
      container_name: calculator
  compute:
      build: ./compute
      image: compute
      environment:
        - VIRTUAL_HOST=compute.localtest.me
  proxy: 
      image: jwilder/nginx-proxy 
      volumes: 
        - /var/run/docker.sock:/tmp/docker.sock:ro 
      ports: 
        - 81:81 
  load-balancer:
      build: ./load-balancer
      image: load-balancer
      volumes: 
        - /var/run/docker.sock:/tmp/docker.sock:ro
      ports:
        - 80:80
      container_name: load-balancer



// command: docker-compose up --scale compute=3 

