version: '3.5'  

services: 
    redis: 
      image: bitnami/redis:latest
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
      container_name: redis
    backend: 
      build:
        context: ./backend
      ports: 
        - "5000"
      container_name: server
      environment:
        - REDIS=redis
        - DB_USERNAME=secret
        - DB_PASSWORD=secret
        - DB_HOST=db
    frontend: 
      build:
        context: ./frontend
      ports: 
        - "5000"
      container_name: client
    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_USER: secret
        POSTGRES_PASSWORD: secret
      volumes:
        - ./data/pg:/var/lib/postgresql/data
      container_name: db
    nginx:
      image: nginx
      container_name: nginx      
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf 
      ports:
        - "80:80"
